image: node:8.6.0

cache:
  paths:
    - node_modules/
before_script:
  - npm install
test:
  stage: test
  script:
    - ./node_modules/@angular/cli/bin/ng lint --type-check && stylelint \"src/**/*.scss\" --syntax scss && htmlhint \"src\" --config .htmlhintrc && ./node_modules/@angular/cli/bin/ng test --single-run --code-coverage
  except:
    - master

# the 'pages' job will deploy and build your site to the 'testci' path
pages:
  stage: deploy
  script:
    - npm run build [-- --env=prod]
  artifacts:
    paths:
      - public
  only:
    - testci # this job will affect only the 'testci' branch
