image: node:6.11.0

cache:
  paths:
    - node_modules/

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - npm install -g @angular/cli
    - npm install

test:
  stage: test
  script:
    - npm run test:ci
  except:
    - master